# Generated by Django 4.2.4 on 2023-11-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.CharField(max_length=255)),
                ('altura', models.TextField(max_length=255)),
                ('peso', models.EmailField(max_length=254)),
            ],
        ),
    ]
