# Generated by Django 4.2.4 on 2023-11-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Coach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dados',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dados',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
